// =============================================================================
// CLINICAL MATRIX — The hardcoded medical brain
// Maps: Symptoms → Linked Diseases → Required Follow-Up Questions → Breed Multipliers
// This is NOT AI-generated at runtime. It's the deterministic backbone.
// =============================================================================

export interface SymptomEntry {
  linked_diseases: string[];
  follow_up_questions: string[];
  red_flags: string[]; // If any of these are true → immediate emergency
  body_systems: string[];
}

export interface DiseaseEntry {
  name: string;
  medical_term: string;
  description: string;
  base_probability: number; // 0-1 baseline
  age_modifier: { puppy: number; adult: number; senior: number }; // multipliers
  urgency: "low" | "moderate" | "high" | "emergency";
  key_differentiators: string[]; // What makes this different from similar conditions
  typical_tests: string[];
  typical_home_care: string[];
}

export interface BreedModifiers {
  [disease: string]: number; // multiplier (1.0 = normal, 2.8 = 2.8x more likely)
}

export interface FollowUpQuestion {
  id: string;
  question_text: string; // Natural language for the LLM to rephrase
  data_type: "boolean" | "string" | "number" | "choice";
  choices?: string[];
  extraction_hint: string; // Helps LLM extract this from free text
  critical: boolean; // Must be answered before diagnosis
}

// --- SYMPTOM → DISEASE + QUESTION MAP ---

export const SYMPTOM_MAP: Record<string, SymptomEntry> = {
  vomiting: {
    linked_diseases: [
      "gastroenteritis",
      "pancreatitis",
      "foreign_body",
      "ibd",
      "gdv",
      "toxin_ingestion",
      "kidney_disease",
    ],
    follow_up_questions: [
      "vomit_duration",
      "vomit_frequency",
      "vomit_blood",
      "vomit_content",
      "toxin_exposure",
      "dietary_change",
      "appetite_status",
    ],
    red_flags: ["vomit_blood", "unproductive_retching", "toxin_confirmed"],
    body_systems: ["gastrointestinal"],
  },
  not_eating: {
    linked_diseases: [
      "gastroenteritis",
      "pancreatitis",
      "foreign_body",
      "kidney_disease",
      "liver_disease",
      "dental_disease",
      "pain_general",
    ],
    follow_up_questions: [
      "appetite_duration",
      "water_intake",
      "weight_loss",
      "treats_accepted",
    ],
    red_flags: ["no_water_24h"],
    body_systems: ["gastrointestinal", "systemic"],
  },
  diarrhea: {
    linked_diseases: [
      "gastroenteritis",
      "pancreatitis",
      "ibd",
      "parasites",
      "colitis",
      "food_allergy",
    ],
    follow_up_questions: [
      "stool_blood",
      "stool_frequency",
      "stool_consistency",
      "diarrhea_duration",
      "dietary_change",
    ],
    red_flags: ["stool_blood_large", "bloody_diarrhea_puppy"],
    body_systems: ["gastrointestinal"],
  },
  limping: {
    linked_diseases: [
      "ccl_rupture",
      "hip_dysplasia",
      "osteoarthritis",
      "soft_tissue_injury",
      "impa",
      "bone_cancer",
      "ivdd",
      "iliopsoas_strain",
      "patellar_luxation",
      "lumbosacral_disease",
    ],
    follow_up_questions: [
      "which_leg",
      "limping_onset",
      "limping_progression",
      "weight_bearing",
      "pain_on_touch",
      "trauma_history",
      "worse_after_rest",
      "swelling_present",
      "warmth_present",
      "prior_limping",
    ],
    red_flags: ["non_weight_bearing", "visible_fracture", "sudden_paralysis"],
    body_systems: ["musculoskeletal"],
  },
  lethargy: {
    linked_diseases: [
      "pain_general",
      "infection",
      "anemia",
      "hypothyroidism",
      "heart_disease",
      "kidney_disease",
      "liver_disease",
      "addisons_disease",
    ],
    follow_up_questions: [
      "lethargy_duration",
      "lethargy_severity",
      "appetite_status",
      "exercise_intolerance",
    ],
    red_flags: ["collapse", "unresponsive"],
    body_systems: ["systemic"],
  },
  coughing: {
    linked_diseases: [
      "kennel_cough",
      "heart_disease",
      "pneumonia",
      "collapsing_trachea",
      "laryngeal_paralysis",
      "lung_cancer",
    ],
    follow_up_questions: [
      "cough_type",
      "cough_duration",
      "cough_timing",
      "exercise_intolerance",
      "breathing_rate",
      "nasal_discharge",
    ],
    red_flags: ["breathing_difficulty", "blue_gums", "cough_blood"],
    body_systems: ["respiratory"],
  },
  difficulty_breathing: {
    linked_diseases: [
      "pneumonia",
      "heart_failure",
      "pleural_effusion",
      "gdv",
      "laryngeal_paralysis",
      "allergic_reaction",
      "trauma_chest",
    ],
    follow_up_questions: [
      "breathing_onset",
      "breathing_rate",
      "gum_color",
      "position_preference",
    ],
    red_flags: ["blue_gums", "collapse", "breathing_onset_sudden"],
    body_systems: ["respiratory", "cardiovascular"],
  },
  excessive_scratching: {
    linked_diseases: [
      "allergic_dermatitis",
      "food_allergy",
      "flea_allergy",
      "ear_infection",
      "hot_spots",
      "mange",
      "yeast_infection",
    ],
    follow_up_questions: [
      "scratch_location",
      "scratch_duration",
      "skin_changes",
      "flea_prevention",
      "diet_change",
      "seasonal_pattern",
    ],
    red_flags: ["face_swelling", "hives_widespread"],
    body_systems: ["dermatologic"],
  },
  drinking_more: {
    linked_diseases: [
      "diabetes",
      "cushings_disease",
      "kidney_disease",
      "pyometra",
      "liver_disease",
      "hypercalcemia",
    ],
    follow_up_questions: [
      "water_amount_change",
      "urination_frequency",
      "urination_accidents",
      "appetite_change",
      "weight_change",
      "spay_status",
    ],
    red_flags: ["pyometra_signs"],
    body_systems: ["endocrine", "renal"],
  },
  trembling: {
    linked_diseases: [
      "pain_general",
      "toxin_ingestion",
      "hypoglycemia",
      "seizure_disorder",
      "addisons_disease",
      "fever",
      "anxiety",
    ],
    follow_up_questions: [
      "trembling_duration",
      "trembling_timing",
      "toxin_exposure",
      "consciousness_level",
      "temperature_feel",
    ],
    red_flags: ["seizure_activity", "toxin_confirmed", "collapse"],
    body_systems: ["neurologic", "systemic"],
  },
  swollen_abdomen: {
    linked_diseases: [
      "gdv",
      "ascites",
      "splenic_mass",
      "pyometra",
      "cushings_disease",
      "pregnancy",
    ],
    follow_up_questions: [
      "abdomen_onset",
      "abdomen_pain",
      "unproductive_retching",
      "spay_status",
      "restlessness",
    ],
    red_flags: ["unproductive_retching", "rapid_onset_distension"],
    body_systems: ["gastrointestinal", "reproductive"],
  },
  blood_in_stool: {
    linked_diseases: [
      "hemorrhagic_gastroenteritis",
      "colitis",
      "parasites",
      "foreign_body",
      "coagulopathy",
      "gi_cancer",
    ],
    follow_up_questions: [
      "blood_color",
      "blood_amount",
      "stool_frequency",
      "toxin_exposure",
      "rat_poison_access",
    ],
    red_flags: ["large_blood_volume", "rat_poison_confirmed", "pale_gums"],
    body_systems: ["gastrointestinal", "hematologic"],
  },
  eye_discharge: {
    linked_diseases: [
      "conjunctivitis",
      "corneal_ulcer",
      "dry_eye",
      "glaucoma",
      "uveitis",
      "entropion",
    ],
    follow_up_questions: [
      "discharge_color",
      "discharge_duration",
      "squinting",
      "eye_redness",
      "vision_changes",
      "trauma_history",
    ],
    red_flags: ["eye_swollen_shut", "eye_bulging", "sudden_blindness"],
    body_systems: ["ophthalmologic"],
  },
  ear_scratching: {
    linked_diseases: [
      "ear_infection_bacterial",
      "ear_infection_yeast",
      "ear_mites",
      "allergic_dermatitis",
      "foreign_body_ear",
      "aural_hematoma",
    ],
    follow_up_questions: [
      "ear_odor",
      "ear_discharge",
      "head_shaking",
      "head_tilt",
      "balance_issues",
      "ear_swelling",
    ],
    red_flags: ["head_tilt_sudden", "balance_loss", "facial_drooping"],
    body_systems: ["dermatologic", "neurologic"],
  },
  weight_loss: {
    linked_diseases: [
      "diabetes",
      "hyperthyroidism",
      "kidney_disease",
      "cancer",
      "ibd",
      "exocrine_pancreatic_insufficiency",
      "parasites",
    ],
    follow_up_questions: [
      "weight_loss_duration",
      "weight_loss_amount",
      "appetite_change",
      "stool_changes",
      "water_intake",
    ],
    red_flags: ["rapid_weight_loss"],
    body_systems: ["systemic", "endocrine"],
  },
  wound_skin_issue: {
    linked_diseases: [
      "wound_infection",
      "abscess",
      "hot_spots",
      "allergic_dermatitis",
      "skin_mass",
      "laceration",
      "autoimmune_skin",
    ],
    follow_up_questions: [
      "wound_location",
      "wound_size",
      "wound_duration",
      "wound_color",
      "wound_discharge",
      "wound_odor",
      "wound_licking",
      "trauma_history",
    ],
    red_flags: ["wound_deep_bleeding", "wound_bone_visible", "wound_spreading_rapidly"],
    body_systems: ["dermatologic", "musculoskeletal"],
  },
};

// --- DISEASE DATABASE ---

export const DISEASE_DB: Record<string, DiseaseEntry> = {
  ccl_rupture: {
    name: "Cranial Cruciate Ligament (CCL) Rupture",
    medical_term: "Cranial Cruciate Ligament Rupture - Partial or Complete",
    description:
      "Tear of the cranial cruciate ligament in the stifle joint, analogous to ACL in humans.",
    base_probability: 0.15,
    age_modifier: { puppy: 0.3, adult: 1.0, senior: 1.8 },
    urgency: "high",
    key_differentiators: [
      "Sudden onset lameness after activity",
      "Weight-bearing but favoring leg",
      "Stifle joint instability on drawer test",
      "Effusion in stifle joint",
    ],
    typical_tests: [
      "Orthopedic examination with cranial drawer test and tibial compression test",
      "Orthogonal radiographs of stifle (lateral and craniocaudal views)",
      "Sedated palpation for subtle partial tears",
    ],
    typical_home_care: [
      "Strict exercise restriction — leash walks only for elimination",
      "Anti-inflammatory protocol as prescribed by vet",
      "Cold therapy 15 min every 4-6 hours for first 48 hours",
    ],
  },
  hip_dysplasia: {
    name: "Hip Dysplasia with Secondary Osteoarthritis",
    medical_term: "Coxofemoral Dysplasia with Secondary Degenerative Joint Disease",
    description:
      "Malformation of the hip joint leading to progressive arthritis. Often subclinical until triggered.",
    base_probability: 0.12,
    age_modifier: { puppy: 0.5, adult: 1.0, senior: 2.2 },
    urgency: "moderate",
    key_differentiators: [
      "Stiffness worse after rest, improves with movement",
      "Pain on hip extension",
      "Bilateral symptoms common",
      "Bunny-hopping gait",
    ],
    typical_tests: [
      "Extended hip radiographs (ventrodorsal hip-extended view)",
      "PennHIP distraction index measurement",
      "OFA hip evaluation",
    ],
    typical_home_care: [
      "Weight management — maintain lean body condition score 4-5/9",
      "Joint supplement: glucosamine 500mg + chondroitin 400mg daily",
      "Low-impact exercise — swimming, controlled leash walks",
    ],
  },
  soft_tissue_injury: {
    name: "Soft Tissue Strain / Muscle Contusion",
    medical_term: "Acute Musculotendinous Strain with Localized Inflammation",
    description: "Muscle or tendon strain from sudden activity. Usually self-limiting.",
    base_probability: 0.25,
    age_modifier: { puppy: 0.8, adult: 1.0, senior: 0.7 },
    urgency: "low",
    key_differentiators: [
      "Acute onset after vigorous activity",
      "Localized pain and warmth",
      "Resolves within 5-7 days with rest",
      "No joint instability",
    ],
    typical_tests: [
      "Physical examination with palpation",
      "Radiographs to rule out fracture if warranted",
    ],
    typical_home_care: [
      "Rest and restricted activity for 5-7 days",
      "Cold therapy for acute phase (first 48 hours)",
      "Gradual return to activity",
    ],
  },
  iliopsoas_strain: {
    name: "Iliopsoas Muscle Strain",
    medical_term: "Iliopsoas Myotendinopathy",
    description:
      "Deep hip flexor injury common in athletic dogs during sudden acceleration/deceleration.",
    base_probability: 0.08,
    age_modifier: { puppy: 0.4, adult: 1.2, senior: 0.6 },
    urgency: "moderate",
    key_differentiators: [
      "Pain on hip extension and internal rotation",
      "Often mistaken for hip joint pathology",
      "Common in active/athletic dogs",
      "Worsens with activity vs improves (opposite of OA)",
    ],
    typical_tests: [
      "Specific iliopsoas palpation under sedation",
      "Musculoskeletal ultrasound of iliopsoas",
      "MRI for chronic cases",
    ],
    typical_home_care: [
      "Strict rest for 2-4 weeks",
      "Physical rehabilitation exercises when cleared",
      "Controlled leash walks only",
    ],
  },
  osteoarthritis: {
    name: "Osteoarthritis",
    medical_term: "Degenerative Joint Disease (DJD)",
    description: "Progressive joint degeneration causing chronic pain and stiffness.",
    base_probability: 0.1,
    age_modifier: { puppy: 0.1, adult: 0.8, senior: 3.0 },
    urgency: "moderate",
    key_differentiators: [
      "Gradual onset over weeks/months",
      "Morning stiffness",
      "Worsens in cold/damp weather",
      "Muscle wasting over affected limb",
    ],
    typical_tests: [
      "Orthogonal joint radiographs",
      "Joint fluid analysis if effusion present",
    ],
    typical_home_care: [
      "Weight management",
      "Omega-3 fatty acid supplementation (EPA/DHA)",
      "Gentle daily exercise",
      "Orthopedic bedding",
    ],
  },
  impa: {
    name: "Immune-Mediated Polyarthritis (IMPA)",
    medical_term: "Immune-Mediated Polyarthritis",
    description:
      "Autoimmune condition causing inflammation in multiple joints simultaneously.",
    base_probability: 0.03,
    age_modifier: { puppy: 0.5, adult: 1.5, senior: 1.0 },
    urgency: "high",
    key_differentiators: [
      "Multiple joints affected simultaneously",
      "Fever, lethargy, appetite loss",
      "Shifting leg lameness",
      "Joint swelling and warmth in multiple locations",
    ],
    typical_tests: [
      "Joint fluid analysis (arthrocentesis) from multiple joints",
      "Complete blood count with differential",
      "ANA titer and rheumatoid factor",
      "Tick-borne disease panel (4Dx)",
    ],
    typical_home_care: [
      "Rest and activity restriction",
      "Monitor temperature twice daily",
      "Track which joints appear affected",
    ],
  },
  bone_cancer: {
    name: "Osteosarcoma",
    medical_term: "Appendicular Osteosarcoma",
    description:
      "Aggressive bone cancer most common in large/giant breeds. Usually affects long bones.",
    base_probability: 0.02,
    age_modifier: { puppy: 0.1, adult: 0.5, senior: 2.5 },
    urgency: "high",
    key_differentiators: [
      "Progressive lameness not improving with rest",
      "Firm swelling at bone site",
      "Pain increasing over weeks",
      "Large/giant breed predisposition",
    ],
    typical_tests: [
      "Orthogonal radiographs of affected limb",
      "Thoracic radiographs (3 views) for metastasis screening",
      "Bone biopsy for definitive diagnosis",
      "Alkaline phosphatase levels",
    ],
    typical_home_care: [
      "Pain management as prescribed",
      "Activity restriction to comfort level",
      "Monitor for pathologic fracture risk",
    ],
  },
  lumbosacral_disease: {
    name: "Lumbosacral Stenosis",
    medical_term: "Degenerative Lumbosacral Stenosis with L7-S1 Nerve Root Compression",
    description: "Compression of nerves at the lumbosacral junction causing hindlimb pain.",
    base_probability: 0.04,
    age_modifier: { puppy: 0.1, adult: 0.6, senior: 2.0 },
    urgency: "moderate",
    key_differentiators: [
      "Pain on lumbosacral palpation and tail elevation",
      "Difficulty rising",
      "Hindlimb weakness bilateral",
      "Fecal/urinary incontinence in advanced cases",
    ],
    typical_tests: [
      "Lumbosacral radiographs",
      "MRI of lumbosacral spine",
      "Neurologic examination",
    ],
    typical_home_care: [
      "Weight management",
      "Avoid jumping and stairs",
      "Ramp access for vehicles/furniture",
    ],
  },
  patellar_luxation: {
    name: "Patellar Luxation",
    medical_term: "Medial or Lateral Patellar Luxation",
    description: "Kneecap slips out of its groove, causing intermittent lameness.",
    base_probability: 0.08,
    age_modifier: { puppy: 1.5, adult: 1.0, senior: 0.8 },
    urgency: "moderate",
    key_differentiators: [
      "Intermittent 'skipping' gait",
      "Sudden non-weight-bearing then spontaneous resolution",
      "More common in small breeds",
      "Palpable luxation on exam",
    ],
    typical_tests: [
      "Orthopedic exam with patellar palpation",
      "Stifle radiographs",
    ],
    typical_home_care: [
      "Weight management",
      "Moderate consistent exercise",
      "Joint supplements",
    ],
  },
  gastroenteritis: {
    name: "Acute Gastroenteritis",
    medical_term: "Acute Gastroenteritis — Dietary Indiscretion vs Infectious",
    description: "Inflammation of stomach/intestines from dietary indiscretion or infection.",
    base_probability: 0.3,
    age_modifier: { puppy: 1.5, adult: 1.0, senior: 0.8 },
    urgency: "moderate",
    key_differentiators: [
      "Vomiting and/or diarrhea",
      "Recent dietary change or garbage access",
      "Self-limiting within 24-48 hours",
      "No abdominal pain on palpation",
    ],
    typical_tests: [
      "Fecal analysis (flotation + direct smear)",
      "CBC and chemistry panel if persists >48h",
      "Abdominal radiographs if foreign body suspected",
    ],
    typical_home_care: [
      "Withhold food 12 hours, then bland diet (boiled chicken + rice, 2:1 ratio)",
      "Small frequent meals — 1/4 portion 4x daily",
      "Ensure hydration — offer Pedialyte or low-sodium broth",
    ],
  },
  pancreatitis: {
    name: "Acute Pancreatitis",
    medical_term: "Acute Pancreatitis",
    description: "Inflammation of the pancreas causing severe abdominal pain and vomiting.",
    base_probability: 0.1,
    age_modifier: { puppy: 0.3, adult: 1.0, senior: 1.8 },
    urgency: "high",
    key_differentiators: [
      "Severe abdominal pain — prayer position",
      "Persistent vomiting",
      "Anorexia",
      "History of fatty food or garbage ingestion",
    ],
    typical_tests: [
      "Canine pancreatic lipase immunoreactivity (cPLI/Spec cPL)",
      "Abdominal ultrasound",
      "CBC and comprehensive chemistry panel",
    ],
    typical_home_care: [
      "NPO (nothing by mouth) until vet evaluation",
      "Low-fat diet long-term once recovered",
      "Monitor for dehydration — check skin turgor and gum moisture",
    ],
  },
  foreign_body: {
    name: "Gastrointestinal Foreign Body",
    medical_term: "Gastrointestinal Foreign Body Obstruction",
    description: "Ingested object blocking the GI tract — surgical emergency if complete obstruction.",
    base_probability: 0.08,
    age_modifier: { puppy: 2.5, adult: 1.0, senior: 0.4 },
    urgency: "emergency",
    key_differentiators: [
      "Persistent vomiting — especially projectile",
      "History of chewing/ingesting objects",
      "Progressive lethargy and anorexia",
      "Abdominal pain on palpation",
    ],
    typical_tests: [
      "Abdominal radiographs (right lateral + VD)",
      "Abdominal ultrasound",
      "Barium contrast study if radiographs inconclusive",
    ],
    typical_home_care: [
      "DO NOT attempt to induce vomiting without veterinary guidance",
      "NPO — nothing by mouth",
      "Seek emergency care immediately if suspected",
    ],
  },
  ibd: {
    name: "Inflammatory Bowel Disease (IBD)",
    medical_term: "Inflammatory Bowel Disease — Lymphoplasmacytic or Eosinophilic",
    description: "Chronic inflammatory condition of the GI tract causing intermittent symptoms.",
    base_probability: 0.06,
    age_modifier: { puppy: 0.3, adult: 1.2, senior: 1.5 },
    urgency: "moderate",
    key_differentiators: [
      "Chronic intermittent vomiting/diarrhea (weeks to months)",
      "Weight loss despite adequate food intake",
      "Fluctuating appetite",
      "Symptoms wax and wane",
    ],
    typical_tests: [
      "GI endoscopy with mucosal biopsies",
      "Cobalamin (B12) and folate levels",
      "Fecal analysis to rule out parasites",
      "Hypoallergenic diet trial (8-12 weeks)",
    ],
    typical_home_care: [
      "Novel protein or hydrolyzed diet trial",
      "Food diary tracking symptoms vs diet",
      "Probiotic supplementation",
    ],
  },
  gdv: {
    name: "Gastric Dilatation-Volvulus (GDV/Bloat)",
    medical_term: "Gastric Dilatation-Volvulus (GDV)",
    description: "Life-threatening twisting of the stomach. Minutes matter.",
    base_probability: 0.02,
    age_modifier: { puppy: 0.2, adult: 1.0, senior: 1.5 },
    urgency: "emergency",
    key_differentiators: [
      "Distended/bloated abdomen",
      "Unproductive retching — trying to vomit but nothing comes up",
      "Restlessness and pacing",
      "Rapid decline — pale gums, weak pulse, collapse",
    ],
    typical_tests: [
      "Right lateral abdominal radiograph — double bubble sign",
      "Emergency stabilization — IV fluids, gastric decompression",
    ],
    typical_home_care: [
      "THIS IS AN EMERGENCY — go to nearest ER vet NOW",
      "Do not wait, do not try home treatment",
      "Call ahead so ER can prepare for surgery",
    ],
  },
  toxin_ingestion: {
    name: "Toxin Ingestion / Poisoning",
    medical_term: "Acute Toxicosis",
    description: "Ingestion of toxic substance — treatment depends on toxin type and timing.",
    base_probability: 0.05,
    age_modifier: { puppy: 2.0, adult: 1.0, senior: 0.6 },
    urgency: "emergency",
    key_differentiators: [
      "Known or suspected access to toxic substance",
      "Acute onset vomiting, trembling, or neurologic signs",
      "Chocolate, xylitol, grapes, rodenticides, medications",
    ],
    typical_tests: [
      "Toxicology screening based on suspected agent",
      "CBC, chemistry, coagulation panel",
      "Activated charcoal if within ingestion window",
    ],
    typical_home_care: [
      "Call ASPCA Poison Control: (888) 426-4435",
      "Do NOT induce vomiting unless directed by vet/poison control",
      "Bring any packaging of suspected toxin to the ER",
    ],
  },
  kidney_disease: {
    name: "Chronic Kidney Disease",
    medical_term: "Chronic Kidney Disease (CKD) — IRIS Staging",
    description: "Progressive loss of kidney function.",
    base_probability: 0.04,
    age_modifier: { puppy: 0.2, adult: 0.5, senior: 3.0 },
    urgency: "high",
    key_differentiators: [
      "Increased water intake and urination",
      "Weight loss and decreased appetite",
      "Vomiting and lethargy in advanced stages",
      "Bad breath (uremic halitosis)",
    ],
    typical_tests: [
      "BUN, creatinine, SDMA",
      "Urinalysis with urine specific gravity",
      "Urine protein:creatinine ratio",
      "Abdominal ultrasound — kidney size and architecture",
    ],
    typical_home_care: [
      "Ensure constant access to fresh water",
      "Renal-specific diet (reduced phosphorus, moderate protein)",
      "Monitor water intake — measure daily",
    ],
  },
  diabetes: {
    name: "Diabetes Mellitus",
    medical_term: "Diabetes Mellitus — Type I (Insulin-Dependent)",
    description: "Inability to regulate blood sugar due to insufficient insulin production.",
    base_probability: 0.03,
    age_modifier: { puppy: 0.1, adult: 1.0, senior: 2.0 },
    urgency: "high",
    key_differentiators: [
      "Increased thirst and urination (PU/PD)",
      "Weight loss despite good appetite",
      "Cataracts (diabetic dogs)",
      "Recurrent urinary tract infections",
    ],
    typical_tests: [
      "Fasting blood glucose",
      "Fructosamine level",
      "Urinalysis — glucosuria and ketonuria",
      "Complete chemistry panel",
    ],
    typical_home_care: [
      "Monitor water intake",
      "Consistent feeding schedule — same time, same amount",
      "Monitor for signs of hypoglycemia or ketoacidosis",
    ],
  },
  allergic_dermatitis: {
    name: "Atopic Dermatitis / Allergic Skin Disease",
    medical_term: "Canine Atopic Dermatitis (CAD)",
    description: "Allergic skin condition causing chronic itching. Environmental or food-triggered.",
    base_probability: 0.15,
    age_modifier: { puppy: 1.5, adult: 1.0, senior: 0.7 },
    urgency: "low",
    key_differentiators: [
      "Chronic itching — face, feet, ears, armpits, groin",
      "Recurrent ear infections",
      "Seasonal pattern (environmental) or constant (food)",
      "Skin redness and secondary infections",
    ],
    typical_tests: [
      "Skin scraping and cytology",
      "Intradermal allergy testing",
      "Elimination diet trial (8-12 weeks)",
    ],
    typical_home_care: [
      "Medicated baths (chlorhexidine or oatmeal-based) 2x weekly",
      "Omega-3 fatty acid supplementation",
      "Flea prevention — consistent monthly application",
      "Food diary if food allergy suspected",
    ],
  },
  ear_infection_bacterial: {
    name: "Bacterial Ear Infection (Otitis Externa)",
    medical_term: "Otitis Externa — Bacterial",
    description: "Infection of the external ear canal. Common secondary to allergies or moisture.",
    base_probability: 0.2,
    age_modifier: { puppy: 0.8, adult: 1.0, senior: 1.2 },
    urgency: "moderate",
    key_differentiators: [
      "Ear odor — foul or yeasty",
      "Brown/yellow/green discharge",
      "Head shaking and ear scratching",
      "Pain on ear manipulation",
    ],
    typical_tests: [
      "Otoscopic examination",
      "Ear cytology — stain and microscopy",
      "Culture and sensitivity if recurrent",
    ],
    typical_home_care: [
      "Do not clean ears until vet evaluates — may have ruptured eardrum",
      "Prevent water entry — no swimming, careful bathing",
      "Complete full course of prescribed medication",
    ],
  },
  heart_disease: {
    name: "Cardiac Disease",
    medical_term:
      "Degenerative Mitral Valve Disease (DMVD) or Dilated Cardiomyopathy (DCM)",
    description: "Heart disease causing reduced cardiac output. Progressive.",
    base_probability: 0.04,
    age_modifier: { puppy: 0.2, adult: 0.5, senior: 2.5 },
    urgency: "high",
    key_differentiators: [
      "Exercise intolerance — tires quickly",
      "Coughing — especially at night or after exercise",
      "Rapid breathing at rest (>30 breaths/min)",
      "Fainting episodes (syncope)",
    ],
    typical_tests: [
      "Thoracic radiographs — heart size (VHS)",
      "Echocardiogram",
      "ProBNP blood test",
      "ECG/Holter monitoring",
    ],
    typical_home_care: [
      "Monitor resting respiratory rate — count breaths for 15 sec × 4, normal <30/min",
      "Restrict strenuous exercise",
      "Low-sodium diet",
    ],
  },
  kennel_cough: {
    name: "Kennel Cough (Infectious Tracheobronchitis)",
    medical_term: "Canine Infectious Respiratory Disease Complex (CIRDC)",
    description: "Highly contagious respiratory infection. Usually self-limiting.",
    base_probability: 0.15,
    age_modifier: { puppy: 2.0, adult: 1.0, senior: 1.3 },
    urgency: "low",
    key_differentiators: [
      "Honking/goose-like dry cough",
      "Recent boarding, grooming, or dog park exposure",
      "Gagging or retching after coughing",
      "Usually eating/drinking normally",
    ],
    typical_tests: [
      "Usually clinical diagnosis based on history",
      "Respiratory PCR panel if severe or not improving",
      "Thoracic radiographs if pneumonia suspected",
    ],
    typical_home_care: [
      "Isolate from other dogs for 10-14 days",
      "Use harness instead of collar — avoid tracheal pressure",
      "Humidifier in resting area",
      "Honey (1 tsp for medium dog) to soothe throat — NOT for puppies <1yr",
    ],
  },
  wound_infection: {
    name: "Wound Infection",
    medical_term: "Infected Traumatic Wound with Secondary Bacterial Contamination",
    description: "Open wound with bacterial infection causing inflammation, pain, discharge, and potential systemic illness.",
    base_probability: 0.25,
    age_modifier: { puppy: 1.2, adult: 1.0, senior: 1.5 },
    urgency: "high",
    key_differentiators: [
      "Purulent discharge — yellow/green pus",
      "Foul odor from wound site",
      "Surrounding erythema and warmth extending beyond wound margins",
      "Pain disproportionate to wound size",
      "Fever, lethargy, or appetite loss in systemic cases",
    ],
    typical_tests: [
      "Wound culture and sensitivity — aerobic and anaerobic",
      "Cytology of wound exudate — stain for bacteria and inflammatory cells",
      "CBC with differential — look for neutrophilia/left shift",
      "Blood glucose if diabetic or immunocompromised",
    ],
    typical_home_care: [
      "Keep wound clean — gentle saline flush (1 tsp salt per 1 cup warm water) 2-3x daily",
      "Prevent licking — E-collar (cone) mandatory 24/7",
      "Monitor for spreading redness — mark the border with a pen to track progression",
      "Do NOT apply hydrogen peroxide or alcohol — these damage healing tissue",
    ],
  },
  abscess: {
    name: "Subcutaneous Abscess",
    medical_term: "Subcutaneous Abscess with Localized Bacterial Infection",
    description: "Pocket of pus under the skin, often from bite wounds or foreign body penetration.",
    base_probability: 0.15,
    age_modifier: { puppy: 0.8, adult: 1.0, senior: 1.2 },
    urgency: "moderate",
    key_differentiators: [
      "Firm, warm, painful swelling that may rupture and drain",
      "Often preceded by a bite wound or puncture",
      "Foul-smelling purulent drainage if ruptured",
      "May cause fever and regional lymph node enlargement",
    ],
    typical_tests: [
      "Fine needle aspirate of mass — cytology",
      "Culture and sensitivity of aspirated material",
      "Ultrasound if deep abscess suspected",
    ],
    typical_home_care: [
      "Warm compress 10-15 min 3-4x daily to encourage drainage",
      "Keep draining abscess clean with saline flush",
      "E-collar to prevent licking",
      "Complete full antibiotic course as prescribed",
    ],
  },
  hot_spots: {
    name: "Acute Moist Dermatitis (Hot Spot)",
    medical_term: "Acute Moist Dermatitis — Pyotraumatic Dermatitis",
    description: "Rapidly developing area of inflamed, infected skin from self-trauma (licking/scratching).",
    base_probability: 0.2,
    age_modifier: { puppy: 0.8, adult: 1.0, senior: 0.9 },
    urgency: "moderate",
    key_differentiators: [
      "Rapidly developing (hours) moist, red, painful lesion",
      "Often under matted fur — may be larger than visible",
      "Self-trauma driven — dog constantly licking/chewing the area",
      "Common in thick-coated breeds especially in warm/humid weather",
    ],
    typical_tests: [
      "Skin scraping to rule out demodex mites",
      "Impression cytology — bacteria and yeast",
      "Flea comb and skin inspection for underlying cause",
    ],
    typical_home_care: [
      "Clip fur around the lesion — 1 inch margin for air exposure",
      "Clean with dilute chlorhexidine solution 2x daily",
      "E-collar is mandatory — self-trauma is the #1 reason they worsen",
      "Keep area dry — no swimming, careful bathing",
    ],
  },
  laceration: {
    name: "Traumatic Laceration",
    medical_term: "Traumatic Laceration with Possible Subcutaneous Tissue Involvement",
    description: "Cut or tear in the skin from trauma. Depth determines whether sutures or surgery are needed.",
    base_probability: 0.2,
    age_modifier: { puppy: 1.3, adult: 1.0, senior: 0.8 },
    urgency: "high",
    key_differentiators: [
      "Visible break in skin continuity",
      "Bleeding (active or recent)",
      "Visible subcutaneous fat or deeper tissues if full-thickness",
      "Clean edges (sharp object) vs ragged edges (bite/tear)",
    ],
    typical_tests: [
      "Wound exploration under sedation to assess depth",
      "Radiographs if penetrating wound or foreign body suspected",
      "Culture if wound is contaminated or old (>6 hours)",
    ],
    typical_home_care: [
      "Apply direct pressure with clean cloth for active bleeding — hold 5+ minutes",
      "Cover loosely with clean bandage — do NOT apply tight tourniquets",
      "Wounds >1cm deep, >2cm long, or on joints need veterinary closure",
      "Do NOT attempt to close or glue wounds at home",
    ],
  },
  skin_mass: {
    name: "Skin Mass / Tumor",
    medical_term: "Cutaneous or Subcutaneous Neoplasia — Type Pending Histopathology",
    description: "Lump or mass on/under the skin. Can be benign (lipoma) or malignant (mast cell tumor, soft tissue sarcoma).",
    base_probability: 0.08,
    age_modifier: { puppy: 0.2, adult: 0.6, senior: 2.5 },
    urgency: "moderate",
    key_differentiators: [
      "New lump/bump that persists >2 weeks",
      "Rapid growth, irregular borders, or color change",
      "Fixed to underlying tissue (concerning) vs freely movable (often benign)",
      "Ulceration or bleeding from mass surface",
    ],
    typical_tests: [
      "Fine needle aspirate with cytology — first-line for ALL skin masses",
      "Incisional or excisional biopsy with histopathology",
      "Staging: thoracic radiographs, abdominal ultrasound, regional lymph node aspirate",
    ],
    typical_home_care: [
      "Measure and photograph the mass weekly to track growth",
      "ANY new mass should be aspirated by a vet — do not wait and watch",
      "Prevent licking/scratching if ulcerated",
    ],
  },
  autoimmune_skin: {
    name: "Autoimmune Skin Disease",
    medical_term: "Pemphigus Foliaceus or Discoid Lupus Erythematosus",
    description: "Immune system attacks the skin causing crusting, ulceration, and depigmentation.",
    base_probability: 0.02,
    age_modifier: { puppy: 0.3, adult: 1.0, senior: 1.3 },
    urgency: "moderate",
    key_differentiators: [
      "Crusting and ulceration on nose, ear tips, footpads",
      "Symmetrical distribution",
      "Depigmentation of nasal planum",
      "Not responsive to antibiotics alone",
    ],
    typical_tests: [
      "Skin biopsy — punch biopsy from lesion margin",
      "Direct immunofluorescence",
      "ANA titer",
      "CBC and chemistry panel",
    ],
    typical_home_care: [
      "Avoid sun exposure — UV worsens many autoimmune skin conditions",
      "Gentle cleaning of crusted areas with saline",
      "Do not attempt to pick or remove crusts forcefully",
    ],
  },
};

// --- BREED RISK MULTIPLIERS ---

export const BREED_MODIFIERS: Record<string, BreedModifiers> = {
  "Golden Retriever": {
    hip_dysplasia: 2.2,
    ccl_rupture: 1.6,
    ibd: 2.8,
    foreign_body: 3.0,
    allergic_dermatitis: 2.0,
    hypothyroidism: 2.5,
    bone_cancer: 2.0,
    ear_infection_bacterial: 2.0,
    heart_disease: 1.5,
    hot_spots: 3.0,
    skin_mass: 1.8,
  },
  "Labrador Retriever": {
    hip_dysplasia: 2.0,
    ccl_rupture: 1.8,
    osteoarthritis: 1.8,
    foreign_body: 3.5,
    allergic_dermatitis: 1.8,
    ear_infection_bacterial: 2.2,
    obesity_related: 2.5,
    hot_spots: 2.8,
    skin_mass: 1.5,
  },
  "German Shepherd": {
    hip_dysplasia: 2.5,
    lumbosacral_disease: 2.8,
    ibd: 2.0,
    impa: 1.5,
    pancreatitis: 1.8,
    degenerative_myelopathy: 3.0,
    perianal_fistula: 4.0,
    wound_infection: 1.3,
    autoimmune_skin: 2.0,
  },
  Bulldog: {
    difficulty_breathing: 4.0,
    allergic_dermatitis: 3.0,
    hip_dysplasia: 2.8,
    patellar_luxation: 2.0,
    ear_infection_bacterial: 2.5,
    cherry_eye: 3.0,
    heat_stroke: 3.5,
    hot_spots: 2.5,
    wound_infection: 1.5,
    autoimmune_skin: 1.8,
  },
  "French Bulldog": {
    difficulty_breathing: 4.5,
    ivdd: 3.0,
    allergic_dermatitis: 3.0,
    ear_infection_bacterial: 2.0,
    heat_stroke: 4.0,
    hot_spots: 2.0,
    wound_infection: 1.8,
    autoimmune_skin: 1.5,
  },
  Dachshund: {
    ivdd: 12.0,
    patellar_luxation: 1.5,
    diabetes: 2.0,
    cushings_disease: 2.0,
    obesity_related: 2.0,
  },
  Poodle: {
    allergic_dermatitis: 2.0,
    ear_infection_bacterial: 2.5,
    addisons_disease: 3.0,
    bloat: 1.8,
    diabetes: 1.5,
  },
  Boxer: {
    heart_disease: 3.0,
    bone_cancer: 2.5,
    allergic_dermatitis: 2.0,
    bloat: 2.0,
    mast_cell_tumor: 3.5,
    skin_mass: 3.0,
    hot_spots: 1.5,
  },
  "Great Dane": {
    gdv: 5.0,
    bone_cancer: 3.0,
    heart_disease: 2.5,
    hip_dysplasia: 2.0,
    wobbler_syndrome: 3.0,
  },
  Rottweiler: {
    ccl_rupture: 2.5,
    bone_cancer: 3.0,
    hip_dysplasia: 2.0,
    heart_disease: 1.8,
    pancreatitis: 1.5,
  },
  "Yorkshire Terrier": {
    patellar_luxation: 3.0,
    collapsing_trachea: 3.5,
    hypoglycemia: 3.0,
    liver_shunt: 3.0,
    dental_disease: 2.5,
  },
  Beagle: {
    ear_infection_bacterial: 2.5,
    ibd: 1.8,
    hypothyroidism: 2.0,
    epilepsy: 2.5,
    obesity_related: 2.0,
  },
  Chihuahua: {
    patellar_luxation: 3.5,
    collapsing_trachea: 2.5,
    heart_disease: 2.0,
    hypoglycemia: 3.0,
    dental_disease: 3.0,
  },
  "Cavalier King Charles Spaniel": {
    heart_disease: 5.0,
    syringomyelia: 4.0,
    ear_infection_bacterial: 2.0,
    allergic_dermatitis: 1.5,
  },
  "Doberman Pinscher": {
    heart_disease: 4.0,
    wobbler_syndrome: 3.0,
    hypothyroidism: 2.5,
    von_willebrands: 3.0,
  },
  "Cocker Spaniel": {
    ear_infection_bacterial: 4.0,
    allergic_dermatitis: 2.5,
    hypothyroidism: 2.0,
    imha: 3.0,
    glaucoma: 2.5,
  },
  "Bernese Mountain Dog": {
    bone_cancer: 4.0,
    hip_dysplasia: 2.0,
    ccl_rupture: 1.5,
    bloat: 2.0,
    histiocytic_sarcoma: 5.0,
  },
  "Siberian Husky": {
    hip_dysplasia: 1.5,
    hypothyroidism: 2.0,
    eye_disorders: 2.5,
    zinc_responsive_dermatosis: 3.0,
  },
  "Shih Tzu": {
    eye_disorders: 3.0,
    ear_infection_bacterial: 2.0,
    dental_disease: 2.5,
    kidney_disease: 1.5,
    allergic_dermatitis: 1.8,
  },
  "Pit Bull": {
    allergic_dermatitis: 3.5,
    hot_spots: 2.0,
    wound_infection: 1.5,
    skin_mass: 1.8,
    ccl_rupture: 2.0,
    hip_dysplasia: 1.5,
    autoimmune_skin: 1.5,
  },
  "Australian Shepherd": {
    hip_dysplasia: 1.8,
    epilepsy: 2.0,
    eye_disorders: 2.5,
    allergic_dermatitis: 1.5,
    autoimmune_skin: 1.5,
  },
  "Border Collie": {
    hip_dysplasia: 1.5,
    epilepsy: 2.5,
    eye_disorders: 2.0,
    allergic_dermatitis: 1.3,
  },
  Pomeranian: {
    patellar_luxation: 3.0,
    collapsing_trachea: 2.5,
    dental_disease: 2.5,
    alopecia: 2.0,
    heart_disease: 1.5,
  },
  Maltese: {
    patellar_luxation: 2.5,
    dental_disease: 3.0,
    liver_shunt: 2.5,
    collapsing_trachea: 2.0,
    allergic_dermatitis: 1.5,
  },
  "Shar Pei": {
    allergic_dermatitis: 4.0,
    hot_spots: 3.0,
    wound_infection: 2.5,
    autoimmune_skin: 2.5,
    ear_infection_bacterial: 3.0,
    eye_disorders: 2.5,
  },
  "West Highland White Terrier": {
    allergic_dermatitis: 4.0,
    hot_spots: 2.5,
    autoimmune_skin: 2.0,
    skin_mass: 1.5,
    liver_disease: 2.0,
  },
};

// --- FOLLOW-UP QUESTION DEFINITIONS ---

export const FOLLOW_UP_QUESTIONS: Record<string, FollowUpQuestion> = {
  // Limping questions
  which_leg: {
    id: "which_leg",
    question_text: "Which leg is affected? Front or back? Left or right?",
    data_type: "string",
    extraction_hint: "leg affected: front/back, left/right",
    critical: true,
  },
  limping_onset: {
    id: "limping_onset",
    question_text:
      "When did the limping start? Was it sudden or gradual?",
    data_type: "string",
    extraction_hint: "onset: sudden/gradual, timeframe",
    critical: true,
  },
  limping_progression: {
    id: "limping_progression",
    question_text:
      "Is the limping getting better, worse, or staying the same since it started?",
    data_type: "choice",
    choices: ["better", "worse", "same"],
    extraction_hint: "progression: better/worse/same",
    critical: true,
  },
  weight_bearing: {
    id: "weight_bearing",
    question_text:
      "Is your dog putting weight on the affected leg, or completely avoiding it?",
    data_type: "choice",
    choices: ["weight_bearing", "partial", "non_weight_bearing"],
    extraction_hint: "weight bearing status on affected leg",
    critical: true,
  },
  pain_on_touch: {
    id: "pain_on_touch",
    question_text:
      "Does your dog react (yelp, pull away, growl) when you touch the affected area?",
    data_type: "boolean",
    extraction_hint: "pain response when area is touched",
    critical: false,
  },
  trauma_history: {
    id: "trauma_history",
    question_text:
      "Was there any specific incident? A fall, jump, rough play, or getting hit?",
    data_type: "string",
    extraction_hint: "any trauma, fall, jump, rough play, or collision",
    critical: true,
  },
  worse_after_rest: {
    id: "worse_after_rest",
    question_text:
      "Is the limping worse when your dog first gets up from resting?",
    data_type: "boolean",
    extraction_hint: "stiffness after rest that improves with movement",
    critical: false,
  },
  swelling_present: {
    id: "swelling_present",
    question_text: "Is there any visible swelling around the affected area?",
    data_type: "boolean",
    extraction_hint: "visible swelling or enlargement",
    critical: false,
  },
  warmth_present: {
    id: "warmth_present",
    question_text:
      "Does the area feel warm or hot compared to the same area on the other side?",
    data_type: "boolean",
    extraction_hint: "warmth or heat at the affected site",
    critical: false,
  },
  prior_limping: {
    id: "prior_limping",
    question_text:
      "Has your dog had any previous episodes of limping or stiffness?",
    data_type: "boolean",
    extraction_hint: "history of prior lameness or stiffness episodes",
    critical: false,
  },

  // Vomiting questions
  vomit_duration: {
    id: "vomit_duration",
    question_text: "How long has the vomiting been going on?",
    data_type: "string",
    extraction_hint: "duration of vomiting in hours or days",
    critical: true,
  },
  vomit_frequency: {
    id: "vomit_frequency",
    question_text: "How many times has your dog vomited?",
    data_type: "string",
    extraction_hint: "number of vomiting episodes",
    critical: true,
  },
  vomit_blood: {
    id: "vomit_blood",
    question_text:
      "Is there any blood in the vomit? It can look red or like coffee grounds.",
    data_type: "boolean",
    extraction_hint: "blood or coffee-ground material in vomit",
    critical: true,
  },
  vomit_content: {
    id: "vomit_content",
    question_text: "What does the vomit look like? Food, bile (yellow), foam, or something else?",
    data_type: "string",
    extraction_hint: "vomit content: food/bile/foam/other",
    critical: false,
  },
  toxin_exposure: {
    id: "toxin_exposure",
    question_text:
      "Could your dog have eaten anything unusual — trash, human food, plants, medications, or chemicals?",
    data_type: "string",
    extraction_hint: "possible toxin or foreign substance exposure",
    critical: true,
  },
  dietary_change: {
    id: "dietary_change",
    question_text: "Any recent food changes, new treats, or table scraps?",
    data_type: "string",
    extraction_hint: "recent diet changes or unusual food",
    critical: false,
  },

  // General questions
  appetite_status: {
    id: "appetite_status",
    question_text: "How is your dog's appetite? Eating normally, less, or not at all?",
    data_type: "choice",
    choices: ["normal", "decreased", "none"],
    extraction_hint: "appetite status: normal/decreased/absent",
    critical: false,
  },
  appetite_duration: {
    id: "appetite_duration",
    question_text: "How long has the appetite been reduced?",
    data_type: "string",
    extraction_hint: "duration of appetite loss",
    critical: true,
  },
  water_intake: {
    id: "water_intake",
    question_text: "Is your dog drinking water normally?",
    data_type: "choice",
    choices: ["normal", "more_than_usual", "less_than_usual", "not_drinking"],
    extraction_hint: "water intake status",
    critical: true,
  },
  lethargy_duration: {
    id: "lethargy_duration",
    question_text: "How long has your dog been lethargic?",
    data_type: "string",
    extraction_hint: "duration of lethargy",
    critical: true,
  },
  lethargy_severity: {
    id: "lethargy_severity",
    question_text:
      "Is your dog slightly less active, or barely moving at all?",
    data_type: "choice",
    choices: ["mild", "moderate", "severe"],
    extraction_hint: "severity of lethargy: mild/moderate/severe",
    critical: true,
  },

  // Stool questions
  stool_blood: {
    id: "stool_blood",
    question_text:
      "Is there blood in the stool? Is it bright red or dark/tarry?",
    data_type: "string",
    extraction_hint: "blood in stool: red/dark/none",
    critical: true,
  },
  stool_frequency: {
    id: "stool_frequency",
    question_text: "How many bowel movements per day?",
    data_type: "string",
    extraction_hint: "frequency of bowel movements",
    critical: false,
  },
  stool_consistency: {
    id: "stool_consistency",
    question_text: "What's the stool consistency? Formed, soft, watery?",
    data_type: "choice",
    choices: ["formed", "soft", "watery", "mucus"],
    extraction_hint: "stool consistency",
    critical: false,
  },
  diarrhea_duration: {
    id: "diarrhea_duration",
    question_text: "How long has the diarrhea been going on?",
    data_type: "string",
    extraction_hint: "duration of diarrhea",
    critical: true,
  },

  // Respiratory questions
  cough_type: {
    id: "cough_type",
    question_text:
      "What does the cough sound like? Dry/honking, wet/productive, or gagging?",
    data_type: "choice",
    choices: ["dry_honking", "wet_productive", "gagging"],
    extraction_hint: "cough type",
    critical: true,
  },
  cough_duration: {
    id: "cough_duration",
    question_text: "How long has the coughing been going on?",
    data_type: "string",
    extraction_hint: "duration of cough",
    critical: true,
  },
  cough_timing: {
    id: "cough_timing",
    question_text: "When does the coughing happen? At rest, after exercise, at night?",
    data_type: "string",
    extraction_hint: "timing pattern of cough",
    critical: false,
  },
  breathing_rate: {
    id: "breathing_rate",
    question_text:
      "Can you count your dog's breaths for 15 seconds while resting? Multiply by 4. Normal is 15-30 per minute.",
    data_type: "number",
    extraction_hint: "respiratory rate at rest",
    critical: false,
  },
  exercise_intolerance: {
    id: "exercise_intolerance",
    question_text:
      "Does your dog tire more easily than usual during walks or play?",
    data_type: "boolean",
    extraction_hint: "exercise intolerance or tiring easily",
    critical: false,
  },
  breathing_onset: {
    id: "breathing_onset",
    question_text: "Did the breathing difficulty start suddenly or gradually?",
    data_type: "choice",
    choices: ["sudden", "gradual"],
    extraction_hint: "onset of breathing difficulty",
    critical: true,
  },
  gum_color: {
    id: "gum_color",
    question_text:
      "What color are your dog's gums? Pink is normal. Blue, white, or bright red is concerning.",
    data_type: "choice",
    choices: ["pink_normal", "pale_white", "blue", "bright_red", "yellow"],
    extraction_hint: "gum/mucous membrane color",
    critical: true,
  },

  // Skin questions
  scratch_location: {
    id: "scratch_location",
    question_text:
      "Where is the scratching focused? Face, ears, paws, belly, all over?",
    data_type: "string",
    extraction_hint: "location of scratching/itching",
    critical: true,
  },
  scratch_duration: {
    id: "scratch_duration",
    question_text: "How long has the scratching been going on?",
    data_type: "string",
    extraction_hint: "duration of scratching",
    critical: true,
  },
  skin_changes: {
    id: "skin_changes",
    question_text:
      "Are there any visible skin changes? Redness, bumps, scabs, hair loss, or hot spots?",
    data_type: "string",
    extraction_hint: "visible skin changes",
    critical: false,
  },
  flea_prevention: {
    id: "flea_prevention",
    question_text: "Is your dog on monthly flea prevention?",
    data_type: "boolean",
    extraction_hint: "flea prevention status",
    critical: false,
  },
  seasonal_pattern: {
    id: "seasonal_pattern",
    question_text: "Does the itching seem seasonal or year-round?",
    data_type: "choice",
    choices: ["seasonal", "year_round"],
    extraction_hint: "seasonal vs year-round pattern",
    critical: false,
  },

  // Drinking questions
  water_amount_change: {
    id: "water_amount_change",
    question_text: "Roughly how much more water is your dog drinking? Double? Triple?",
    data_type: "string",
    extraction_hint: "estimated increase in water consumption",
    critical: true,
  },
  urination_frequency: {
    id: "urination_frequency",
    question_text: "Is your dog urinating more often than usual?",
    data_type: "boolean",
    extraction_hint: "increased urination frequency",
    critical: true,
  },
  urination_accidents: {
    id: "urination_accidents",
    question_text: "Any urinary accidents in the house (previously housetrained)?",
    data_type: "boolean",
    extraction_hint: "urinary accidents or incontinence",
    critical: false,
  },
  weight_change: {
    id: "weight_change",
    question_text: "Has your dog gained or lost weight recently?",
    data_type: "string",
    extraction_hint: "recent weight change",
    critical: false,
  },
  spay_status: {
    id: "spay_status",
    question_text: "Is your dog spayed/neutered?",
    data_type: "boolean",
    extraction_hint: "spay/neuter status",
    critical: true,
  },

  // Ear questions
  ear_odor: {
    id: "ear_odor",
    question_text: "Is there a smell coming from the ears? Sweet, foul, or yeasty?",
    data_type: "string",
    extraction_hint: "ear odor type",
    critical: false,
  },
  ear_discharge: {
    id: "ear_discharge",
    question_text: "Is there any discharge from the ears? What color?",
    data_type: "string",
    extraction_hint: "ear discharge presence and color",
    critical: true,
  },
  head_shaking: {
    id: "head_shaking",
    question_text: "Is your dog shaking their head frequently?",
    data_type: "boolean",
    extraction_hint: "head shaking behavior",
    critical: false,
  },
  head_tilt: {
    id: "head_tilt",
    question_text: "Is there a head tilt — where the head stays tilted to one side?",
    data_type: "boolean",
    extraction_hint: "persistent head tilt",
    critical: true,
  },
  balance_issues: {
    id: "balance_issues",
    question_text: "Any loss of balance, stumbling, or walking in circles?",
    data_type: "boolean",
    extraction_hint: "vestibular signs: imbalance, circling",
    critical: true,
  },

  // General systemic
  weight_loss: {
    id: "weight_loss",
    question_text: "Have you noticed any weight loss recently?",
    data_type: "boolean",
    extraction_hint: "whether the pet has lost weight",
    critical: false,
  },
  weight_loss_duration: {
    id: "weight_loss_duration",
    question_text: "Over what time period has the weight loss occurred?",
    data_type: "string",
    extraction_hint: "timeframe of weight loss",
    critical: true,
  },
  weight_loss_amount: {
    id: "weight_loss_amount",
    question_text: "Roughly how much weight has been lost?",
    data_type: "string",
    extraction_hint: "estimated weight loss amount",
    critical: false,
  },
  appetite_change: {
    id: "appetite_change",
    question_text: "Has appetite increased, decreased, or stayed normal with the weight loss?",
    data_type: "choice",
    choices: ["increased", "decreased", "normal"],
    extraction_hint: "appetite change with weight loss",
    critical: true,
  },
  nasal_discharge: {
    id: "nasal_discharge",
    question_text: "Is there any nasal discharge? Clear, colored, or bloody?",
    data_type: "string",
    extraction_hint: "nasal discharge type",
    critical: false,
  },
  trembling_duration: {
    id: "trembling_duration",
    question_text: "How long has the trembling been going on?",
    data_type: "string",
    extraction_hint: "duration of trembling",
    critical: true,
  },
  trembling_timing: {
    id: "trembling_timing",
    question_text: "Is the trembling constant or does it come and go?",
    data_type: "choice",
    choices: ["constant", "intermittent"],
    extraction_hint: "trembling pattern",
    critical: false,
  },
  consciousness_level: {
    id: "consciousness_level",
    question_text: "Is your dog alert and responsive, or dull/unresponsive?",
    data_type: "choice",
    choices: ["alert", "dull", "unresponsive"],
    extraction_hint: "level of consciousness",
    critical: true,
  },
  temperature_feel: {
    id: "temperature_feel",
    question_text: "Do your dog's ears feel warmer than usual? This can indicate a fever.",
    data_type: "boolean",
    extraction_hint: "subjective fever assessment",
    critical: false,
  },
  abdomen_onset: {
    id: "abdomen_onset",
    question_text: "When did you first notice the abdominal swelling?",
    data_type: "string",
    extraction_hint: "onset of abdominal distension",
    critical: true,
  },
  abdomen_pain: {
    id: "abdomen_pain",
    question_text: "Does your dog seem painful when you touch the belly area?",
    data_type: "boolean",
    extraction_hint: "abdominal pain on palpation",
    critical: true,
  },
  unproductive_retching: {
    id: "unproductive_retching",
    question_text:
      "Is your dog trying to vomit but nothing comes up? This is a potential emergency sign.",
    data_type: "boolean",
    extraction_hint: "unproductive retching — trying to vomit with no output",
    critical: true,
  },
  restlessness: {
    id: "restlessness",
    question_text: "Is your dog restless — pacing, unable to settle, or looking at their belly?",
    data_type: "boolean",
    extraction_hint: "restlessness or inability to get comfortable",
    critical: false,
  },
  treats_accepted: {
    id: "treats_accepted",
    question_text: "Will your dog take treats or favorite foods even if refusing regular meals?",
    data_type: "boolean",
    extraction_hint: "whether dog accepts treats despite reduced appetite",
    critical: false,
  },
  stool_changes: {
    id: "stool_changes",
    question_text: "Any changes in stool — color, consistency, or frequency?",
    data_type: "string",
    extraction_hint: "stool changes",
    critical: false,
  },

  // Eye questions
  discharge_color: {
    id: "discharge_color",
    question_text: "What color is the eye discharge? Clear, white, yellow, or green?",
    data_type: "string",
    extraction_hint: "eye discharge color",
    critical: true,
  },
  discharge_duration: {
    id: "discharge_duration",
    question_text: "How long has the eye discharge been present?",
    data_type: "string",
    extraction_hint: "duration of eye discharge",
    critical: true,
  },
  squinting: {
    id: "squinting",
    question_text: "Is your dog squinting or holding the eye shut?",
    data_type: "boolean",
    extraction_hint: "squinting or blepharospasm",
    critical: true,
  },
  eye_redness: {
    id: "eye_redness",
    question_text: "Is the white part of the eye red or bloodshot?",
    data_type: "boolean",
    extraction_hint: "conjunctival redness",
    critical: false,
  },
  vision_changes: {
    id: "vision_changes",
    question_text: "Have you noticed any changes in vision — bumping into things or hesitating?",
    data_type: "boolean",
    extraction_hint: "signs of vision impairment",
    critical: false,
  },

  // Blood in stool
  blood_color: {
    id: "blood_color",
    question_text: "Is the blood bright red or dark/tarry? Bright red = lower GI, dark = upper GI.",
    data_type: "choice",
    choices: ["bright_red", "dark_tarry"],
    extraction_hint: "color of blood in stool",
    critical: true,
  },
  blood_amount: {
    id: "blood_amount",
    question_text: "How much blood? Streaks on surface, mixed in, or mostly blood?",
    data_type: "choice",
    choices: ["streaks", "mixed_in", "mostly_blood"],
    extraction_hint: "amount of blood in stool",
    critical: true,
  },
  rat_poison_access: {
    id: "rat_poison_access",
    question_text: "Could your dog have had access to rat poison or rodent bait stations?",
    data_type: "boolean",
    extraction_hint: "rodenticide access",
    critical: true,
  },

  // Abdomen
  ear_swelling: {
    id: "ear_swelling",
    question_text: "Is the ear flap puffy or swollen like a pillow?",
    data_type: "boolean",
    extraction_hint: "aural hematoma - ear flap swelling",
    critical: false,
  },
  position_preference: {
    id: "position_preference",
    question_text:
      "Is your dog preferring a specific position — sitting upright, neck extended, or refusing to lie down?",
    data_type: "string",
    extraction_hint: "positional preference indicating orthopnea",
    critical: false,
  },
  diet_change: {
    id: "diet_change",
    question_text: "Any recent changes to diet or new foods introduced?",
    data_type: "string",
    extraction_hint: "recent dietary changes",
    critical: false,
  },

  // Wound / skin issue questions
  wound_location: {
    id: "wound_location",
    question_text: "Where exactly on the body is the wound or skin issue? Which leg, side, or area?",
    data_type: "string",
    extraction_hint: "body location of wound or skin lesion",
    critical: true,
  },
  wound_size: {
    id: "wound_size",
    question_text: "How big is the affected area? Compare to a coin, golf ball, or your palm.",
    data_type: "string",
    extraction_hint: "approximate size of wound or lesion",
    critical: true,
  },
  wound_duration: {
    id: "wound_duration",
    question_text: "How long has this wound or skin issue been present? Is it getting bigger or staying the same?",
    data_type: "string",
    extraction_hint: "duration and progression of the wound",
    critical: true,
  },
  wound_color: {
    id: "wound_color",
    question_text: "What color is the wound or surrounding skin? Red, pink, dark, yellowish, or any unusual color?",
    data_type: "string",
    extraction_hint: "color of wound or affected skin area",
    critical: false,
  },
  wound_discharge: {
    id: "wound_discharge",
    question_text: "Is there any discharge from the wound — pus, clear fluid, or blood?",
    data_type: "choice",
    choices: ["none", "clear_fluid", "pus", "blood", "mixed"],
    extraction_hint: "type of wound discharge",
    critical: true,
  },
  wound_odor: {
    id: "wound_odor",
    question_text: "Does the wound have any smell? A bad odor can indicate infection.",
    data_type: "boolean",
    extraction_hint: "presence of wound odor suggesting infection",
    critical: false,
  },
  wound_licking: {
    id: "wound_licking",
    question_text: "Is your pet constantly licking, biting, or scratching at the area?",
    data_type: "boolean",
    extraction_hint: "self-trauma behavior - licking or chewing at wound",
    critical: true,
  },
};
