import type { SymptomCheckEntry } from "@/components/timeline/types";

/** Stable id for Biscuit in analytics demo data. */
export const DEMO_PET_VET821_ID = "demo-pet-vet-821";

const PET2_ID = "demo-pet-vet-821-mittens";

/** Rich demo set for the analytics dashboard (multiple pets, varied dates). */
export const DEMO_ANALYTICS_SYMPTOM_ENTRIES: SymptomCheckEntry[] = [
  {
    id: "demo-an-1",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2026, 3, 5, 10, 30).toISOString(),
    primary_symptom: "Vomiting and lethargy",
    severity: "serious",
    urgency: "urgent",
    top_diagnosis: "Gastroenteritis",
    confidence: 0.82,
    report_summary:
      "Acute vomiting with reduced energy — monitor hydration and seek vet if vomiting persists beyond 12h.",
  },
  {
    id: "demo-an-2",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2026, 3, 1, 14, 0).toISOString(),
    primary_symptom: "Excessive scratching",
    severity: "moderate",
    urgency: "schedule",
    top_diagnosis: "Seasonal allergies",
    confidence: 0.71,
    report_summary: "Pruritus with ear redness — parasite control and vet visit if otitis signs develop.",
  },
  {
    id: "demo-an-3",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2026, 2, 20, 9, 15).toISOString(),
    primary_symptom: "Mild limp after play",
    severity: "mild",
    urgency: "monitor",
    top_diagnosis: "Soft tissue strain",
    confidence: 0.68,
    report_summary: "Brief lameness after exercise — rest and recheck gait within 48 hours.",
  },
  {
    id: "demo-an-4",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2026, 2, 8, 16, 45).toISOString(),
    primary_symptom: "Loose stool",
    severity: "moderate",
    urgency: "schedule",
    top_diagnosis: "Dietary indiscretion",
    confidence: 0.64,
    report_summary: "Intermittent soft stools — bland diet transition and watch for blood or dehydration.",
  },
  {
    id: "demo-an-5",
    pet_id: PET2_ID,
    pet_name: "Mittens",
    created_at: new Date(2026, 3, 4, 11, 0).toISOString(),
    primary_symptom: "Coughing after running",
    severity: "moderate",
    urgency: "schedule",
    top_diagnosis: "Feline asthma",
    confidence: 0.59,
    report_summary: "Episodic cough — reduce triggers and discuss inhaler therapy with your veterinarian.",
  },
  {
    id: "demo-an-6",
    pet_id: PET2_ID,
    pet_name: "Mittens",
    created_at: new Date(2026, 2, 25, 8, 20).toISOString(),
    primary_symptom: "Sneezing and watery eyes",
    severity: "mild",
    urgency: "monitor",
    top_diagnosis: "Upper respiratory irritation",
    confidence: 0.55,
    report_summary: "Mild URI signs — humidification and isolate from other cats if discharge worsens.",
  },
  {
    id: "demo-an-7",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2026, 1, 12, 13, 30).toISOString(),
    primary_symptom: "Ear shaking",
    severity: "moderate",
    urgency: "schedule",
    top_diagnosis: "Otitis externa",
    confidence: 0.61,
    report_summary: "Head shake and ear odor — cytology and cleaning per vet; avoid cotton swabs deep in canal.",
  },
  {
    id: "demo-an-8",
    pet_id: PET2_ID,
    pet_name: "Mittens",
    created_at: new Date(2026, 1, 5, 17, 0).toISOString(),
    primary_symptom: "Not eating for 24h",
    severity: "serious",
    urgency: "urgent",
    top_diagnosis: "Hepatic lipidosis risk",
    confidence: 0.73,
    report_summary: "Anorexia in a cat warrants prompt veterinary evaluation — do not delay if hiding or vomiting.",
  },
  {
    id: "demo-an-9",
    pet_id: DEMO_PET_VET821_ID,
    pet_name: "Biscuit",
    created_at: new Date(2025, 11, 18, 10, 0).toISOString(),
    primary_symptom: "Pale gums after hike",
    severity: "critical",
    urgency: "emergency",
    top_diagnosis: "Heat exhaustion",
    confidence: 0.77,
    report_summary: "Possible heat stress — cool gradually and seek emergency care if collapse or vomiting.",
  },
];
