"use client";

import { useState, useCallback, useMemo, useSyncExternalStore } from "react";
import {
  Copy, Check, Share2, Printer,
  FileText, Shield, Users,
} from "lucide-react";
import Card from "@/components/ui/card";
import Button from "@/components/ui/button";
import Badge from "@/components/ui/badge";
import { useAppStore } from "@/store/app-store";
import {
  loadCare, getChangeScore, generateVetPacketText,
  type CareState, type VetPacket,
} from "@/lib/care-engine/store";

const hydrate = useSyncExternalStore.bind(null, () => () => {}, () => true, () => false);

type PacketType = VetPacket["type"];

const PACKET_TYPES: { id: PacketType; label: string; description: string; emoji: string }[] = [
  { id: "vet_visit", label: "Vet Visit Packet", description: "Normal appointment prep", emoji: "🏥" },
  { id: "emergency", label: "Emergency Packet", description: "ER visit — fast context", emoji: "🚨" },
  { id: "med_review", label: "Medication Review", description: "New med or side effect concern", emoji: "💊" },
  { id: "quality_of_life", label: "Quality-of-Life Packet", description: "End-of-life conversation", emoji: "💛" },
  { id: "sitter_handoff", label: "Sitter / Family Handoff", description: "Boarding, pet sitter, family member", emoji: "👥" },
];

const HANDOFF_SECTIONS = [
  { id: "feeding", label: "Feeding Schedule", placeholder: "e.g. 1 cup kibble at 7 AM and 5 PM, no table scraps" },
  { id: "meds", label: "Medication Instructions", placeholder: "e.g. Carprofen 75mg with breakfast, Gabapentin 100mg at 8 PM" },
  { id: "walks", label: "Walk / Exercise Routine", placeholder: "e.g. 15 min walk morning and evening, avoid stairs" },
  { id: "bathroom", label: "Bathroom Routine", placeholder: "e.g. Let out after meals, may have accidents overnight" },
  { id: "anxiety", label: "Anxiety / Behavior Notes", placeholder: "e.g. Anxious during storms, paces at night — this is normal for him" },
  { id: "emergency", label: "If Something Goes Wrong", placeholder: "e.g. Call me first. If can't reach me, take to Valley Emergency Vet" },
];

export default function VetPrepPage() {
  const { activePet } = useAppStore();
  const petName = activePet?.name ?? "Cooper";
  const ready = hydrate();

  const care: CareState = useMemo(() => loadCare(petName), [petName]);
  const cs = useMemo(() => getChangeScore(care), [care]);

  const [activeTab, setActiveTab] = useState<"packet" | "handoff">("packet");
  const [selectedType, setSelectedType] = useState<PacketType>("vet_visit");
  const [copied, setCopied] = useState(false);
  const [concerns, setConcerns] = useState<string[]>([]);
  const [newConcern, setNewConcern] = useState("");
  const [handoffFields, setHandoffFields] = useState<Record<string, string>>({});
  const [handoffCopied, setHandoffCopied] = useState(false);

  const packetText = useMemo(() => generateVetPacketText(care, selectedType), [care, selectedType]);

  const handleCopyPacket = useCallback(async () => {
    const full = concerns.length > 0
      ? `${packetText}\n\nConcerns to Discuss:\n${concerns.map((c) => `  • ${c}`).join("\n")}`
      : packetText;
    try { await navigator.clipboard.writeText(full); } catch { /* */ }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [packetText, concerns]);

  const handleAddConcern = useCallback(() => {
    const text = newConcern.trim();
    if (!text) return;
    setConcerns((prev) => [...prev, text]);
    setNewConcern("");
  }, [newConcern]);

  const handoffText = useMemo(() => {
    const lines = [`=== ${petName}'s Care Handoff ===`, `Generated: ${new Date().toLocaleDateString()}`, ""];
    for (const s of HANDOFF_SECTIONS) {
      if (handoffFields[s.id]?.trim()) {
        lines.push(`${s.label}:`);
        lines.push(`  ${handoffFields[s.id]}`);
        lines.push("");
      }
    }
    lines.push("— Generated by PawVital AI");
    return lines.join("\n");
  }, [petName, handoffFields]);

  const handleCopyHandoff = useCallback(async () => {
    try { await navigator.clipboard.writeText(handoffText); } catch { /* */ }
    setHandoffCopied(true);
    setTimeout(() => setHandoffCopied(false), 2000);
  }, [handoffText]);

  if (!ready) return <div className="flex items-center justify-center py-24 text-gray-400">Loading...</div>;

  const recentSymptoms = care.symptomLog.slice(0, 5);
  const activePlans = care.plans.filter((p) => p.status === "active");

  return (
    <div className="mx-auto max-w-3xl space-y-6 pb-12">
      <div>
        <h1 className="text-2xl font-black text-gray-900">Vet Prep</h1>
        <p className="text-sm text-gray-500">Generate a vet-ready summary or sitter handoff for {petName}</p>
      </div>

      {/* Tab switcher */}
      <div className="flex rounded-xl bg-gray-100 p-1">
        <button onClick={() => setActiveTab("packet")}
          className={`flex-1 rounded-lg py-2.5 text-sm font-semibold transition-all ${activeTab === "packet" ? "bg-white text-gray-900 shadow-sm" : "text-gray-500"}`}
        >
          <FileText className="inline h-4 w-4 mr-1.5" />Vet Packet
        </button>
        <button onClick={() => setActiveTab("handoff")}
          className={`flex-1 rounded-lg py-2.5 text-sm font-semibold transition-all ${activeTab === "handoff" ? "bg-white text-gray-900 shadow-sm" : "text-gray-500"}`}
        >
          <Users className="inline h-4 w-4 mr-1.5" />Care Handoff
        </button>
      </div>

      {activeTab === "packet" && (
        <>
          {/* Packet type selector */}
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {PACKET_TYPES.map((t) => (
              <button key={t.id} onClick={() => setSelectedType(t.id)}
                className={`flex items-center gap-3 rounded-xl border-2 p-3.5 text-left transition-all ${
                  selectedType === t.id ? "border-indigo-500 bg-indigo-50" : "border-gray-200 hover:border-indigo-200"
                }`}
              >
                <span className="text-xl">{t.emoji}</span>
                <div>
                  <p className="text-sm font-semibold text-gray-900">{t.label}</p>
                  <p className="text-xs text-gray-500">{t.description}</p>
                </div>
              </button>
            ))}
          </div>

          {/* Add concerns */}
          <Card className="p-4">
            <p className="text-sm font-semibold text-gray-800 mb-2">Your concerns</p>
            <div className="flex gap-2">
              <input type="text" value={newConcern} onChange={(e) => setNewConcern(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleAddConcern()}
                placeholder="e.g. Limping more after walks lately"
                className="flex-1 rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-indigo-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
              <Button onClick={handleAddConcern} disabled={!newConcern.trim()} size="sm">Add</Button>
            </div>
            {concerns.length > 0 && (
              <ul className="mt-2 space-y-1">
                {concerns.map((c, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-gray-700">
                    <span className="h-1.5 w-1.5 rounded-full bg-indigo-500 shrink-0" />{c}
                    <button onClick={() => setConcerns((prev) => prev.filter((_, j) => j !== i))} className="ml-auto text-gray-400 hover:text-red-500 text-xs">×</button>
                  </li>
                ))}
              </ul>
            )}
          </Card>

          {/* Generated packet preview */}
          <Card className="overflow-hidden">
            <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-5 py-4">
              <p className="text-sm text-white/80">{petName}&apos;s {PACKET_TYPES.find((t) => t.id === selectedType)?.label}</p>
              <div className="flex items-center justify-between mt-1">
                <p className="text-xl font-black text-white">Health Score: {cs.score}/100</p>
                <Badge variant={cs.trend === "improving" ? "success" : cs.trend === "declining" ? "danger" : "info"} className="bg-white/20 text-white">{cs.trend}</Badge>
              </div>
            </div>
            <div className="p-5 space-y-3">
              {cs.changes.length > 0 && (
                <div className="rounded-xl bg-amber-50 border border-amber-200 p-3">
                  <p className="text-xs font-bold text-amber-800 uppercase mb-1">Changes Noticed</p>
                  {cs.changes.map((c, i) => <p key={i} className="text-sm text-amber-900">• {c}</p>)}
                </div>
              )}
              {recentSymptoms.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-gray-500 uppercase mb-1">Recent Symptoms</p>
                  {recentSymptoms.map((s) => (
                    <p key={s.id} className="text-sm text-gray-700">{s.date.slice(5)} — {s.symptom} ({s.verdict})</p>
                  ))}
                </div>
              )}
              {activePlans.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-gray-500 uppercase mb-1">Active Care Plans</p>
                  {activePlans.map((p) => (
                    <p key={p.id} className="text-sm text-gray-700">{p.title} — {p.checkIns.length} check-ins</p>
                  ))}
                </div>
              )}
              {concerns.length > 0 && (
                <div>
                  <p className="text-xs font-bold text-gray-500 uppercase mb-1">Your Concerns</p>
                  {concerns.map((c, i) => <p key={i} className="text-sm text-gray-700">• {c}</p>)}
                </div>
              )}
            </div>
            <div className="border-t border-gray-100 px-5 py-3 flex gap-2">
              <Button variant="outline" size="sm" onClick={handleCopyPacket}>
                {copied ? <><Check className="mr-1 h-3 w-3" />Copied</> : <><Copy className="mr-1 h-3 w-3" />Copy</>}
              </Button>
              <Button variant="outline" size="sm" onClick={() => window.print()}>
                <Printer className="mr-1 h-3 w-3" />Print
              </Button>
              <Button size="sm">
                <Share2 className="mr-1 h-3 w-3" />Share
              </Button>
            </div>
          </Card>
        </>
      )}

      {activeTab === "handoff" && (
        <>
          <Card className="p-5">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="h-5 w-5 text-blue-600" />
              <div>
                <p className="text-sm font-bold text-gray-900">Care Handoff for {petName}</p>
                <p className="text-xs text-gray-500">Fill out what the sitter / family member needs to know</p>
              </div>
            </div>
            <div className="space-y-4">
              {HANDOFF_SECTIONS.map((s) => (
                <div key={s.id}>
                  <label className="text-sm font-medium text-gray-800 block mb-1">{s.label}</label>
                  <textarea
                    value={handoffFields[s.id] ?? ""}
                    onChange={(e) => setHandoffFields((prev) => ({ ...prev, [s.id]: e.target.value }))}
                    placeholder={s.placeholder}
                    rows={2}
                    className="w-full resize-none rounded-xl border border-gray-200 px-4 py-2.5 text-sm focus:border-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>
              ))}
            </div>
          </Card>

          <div className="flex gap-2">
            <Button variant="outline" onClick={handleCopyHandoff}>
              {handoffCopied ? <><Check className="mr-1 h-4 w-4" />Copied</> : <><Copy className="mr-1 h-4 w-4" />Copy Handoff</>}
            </Button>
            <Button variant="outline" onClick={() => window.print()}>
              <Printer className="mr-1 h-4 w-4" />Print
            </Button>
            <Button>
              <Share2 className="mr-1 h-4 w-4" />Share via Text
            </Button>
          </div>
        </>
      )}
    </div>
  );
}
