import { StyleSheet } from "@react-pdf/renderer";

/** PawVital brand tokens for React-PDF (system fonts only) */
export const brand = {
  emerald: "#059669",
  emeraldDark: "#047857",
  emeraldLight: "#d1fae5",
  amber: "#d97706",
  amberLight: "#fef3c7",
  orange: "#ea580c",
  orangeLight: "#ffedd5",
  red: "#dc2626",
  redLight: "#fee2e2",
  gray900: "#111827",
  gray700: "#374151",
  gray600: "#4b5563",
  gray500: "#6b7280",
  gray200: "#e5e7eb",
  gray100: "#f3f4f6",
  white: "#ffffff",
};

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 10,
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 40,
    color: brand.gray900,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: brand.emerald,
  },
  logoMark: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: brand.emerald,
  },
  logoText: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    color: brand.emeraldDark,
  },
  sectionTitle: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: brand.emeraldDark,
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  body: {
    fontSize: 10,
    lineHeight: 1.45,
    color: brand.gray700,
  },
  bodySmall: {
    fontSize: 8,
    lineHeight: 1.4,
    color: brand.gray600,
  },
  severityBand: {
    padding: 12,
    borderRadius: 6,
    marginBottom: 10,
    borderWidth: 1,
  },
  alertBox: {
    marginBottom: 10,
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
  },
  alertBoxEmergency: {
    backgroundColor: brand.redLight,
    borderColor: brand.red,
  },
  alertBoxUrgent: {
    backgroundColor: brand.orangeLight,
    borderColor: brand.orange,
  },
  alertTitle: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: brand.gray900,
  },
  badge: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: "flex-start",
    marginTop: 4,
  },
  table: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: brand.gray200,
    borderRadius: 4,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: brand.gray200,
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  colCondition: { width: "38%" },
  colLike: { width: "18%" },
  colBar: { width: "44%" },
  probBarTrack: {
    height: 6,
    backgroundColor: brand.gray200,
    borderRadius: 3,
    marginTop: 4,
    overflow: "hidden",
  },
  probBarFill: {
    height: 6,
    backgroundColor: brand.emerald,
    borderRadius: 3,
  },
  listItem: {
    flexDirection: "row",
    marginBottom: 4,
    paddingLeft: 4,
  },
  bullet: {
    width: 10,
    fontFamily: "Helvetica-Bold",
    color: brand.emerald,
  },
  evidenceBox: {
    padding: 8,
    marginBottom: 6,
    backgroundColor: "#f0f9ff",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#bae6fd",
  },
  handoffBox: {
    padding: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: brand.red,
    backgroundColor: brand.redLight,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: brand.gray200,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: brand.gray500,
  },
  qrPlaceholder: {
    marginTop: 8,
    padding: 8,
    backgroundColor: brand.gray100,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: brand.gray200,
    borderStyle: "dashed",
  },
  disclaimer: {
    marginTop: 12,
    padding: 10,
    backgroundColor: brand.gray100,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: brand.gray200,
  },
});
