import { Document, Page, View, Text } from "@react-pdf/renderer";
import type {
  VetTimelineData,
  VetTimelineEntry,
  VetTimelineTone,
} from "@/lib/analytics/vet-timeline";
import { brand, pdfStyles } from "./styles";

const TONE_COLORS: Record<VetTimelineTone, { bg: string; border: string }> = {
  normal: { bg: brand.gray100, border: brand.gray200 },
  changed: { bg: brand.amberLight, border: brand.amber },
  alert: { bg: brand.redLight, border: brand.red },
};

const SOURCE_LABEL: Record<VetTimelineEntry["source"], string> = {
  symptom_check: "Symptom check",
  daily_log: "Daily log",
  journal: "Journal",
  medication: "Medication",
};

/**
 * Vet-Ready Timeline PDF — an owner-reported health summary a pet owner can hand
 * to their vet. Owner observations only; never a diagnosis or clinical record.
 */
export function VetTimelineDocument({
  data,
  petName,
  generatedAt,
}: {
  data: VetTimelineData;
  petName: string;
  generatedAt: string;
}) {
  return (
    <Document
      title={`PawVital vet summary — ${petName}`}
      author="PawVital"
      subject="Owner-reported health summary"
    >
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.headerRow}>
          <View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}>
            <View style={pdfStyles.logoMark} />
            <Text style={pdfStyles.logoText}>PawVital</Text>
          </View>
          <Text style={pdfStyles.bodySmall}>Owner Health Summary</Text>
        </View>

        <Text style={{ fontSize: 15, fontFamily: "Helvetica-Bold", color: brand.gray900 }}>
          {petName}
        </Text>
        <Text style={[pdfStyles.bodySmall, { marginTop: 2 }]}>
          Generated from owner-logged data only — not a clinical record. All
          observations are owner-reported.
        </Text>

        {/* What to tell the vet */}
        {data.vetSummary ? (
          <>
            <Text style={pdfStyles.sectionTitle}>What to tell your vet</Text>
            <View style={pdfStyles.reasonBox}>
              <Text style={pdfStyles.body}>{data.vetSummary}</Text>
            </View>
          </>
        ) : null}

        {/* Recurring signs */}
        {data.recurringSymptoms.length > 0 ? (
          <>
            <Text style={pdfStyles.sectionTitle}>Recurring signs</Text>
            {data.recurringSymptoms.map((s, i) => (
              <View key={i} style={pdfStyles.listItem}>
                <Text style={pdfStyles.bullet}>•</Text>
                <Text style={pdfStyles.body}>{s}</Text>
              </View>
            ))}
          </>
        ) : null}

        {/* History */}
        <Text style={pdfStyles.sectionTitle}>
          History ({data.entries.length} {data.entries.length === 1 ? "entry" : "entries"}, newest first)
        </Text>
        {data.entries.length === 0 ? (
          <Text style={pdfStyles.body}>No logged history yet.</Text>
        ) : (
          data.entries.map((e, i) => {
            const c = TONE_COLORS[e.tone];
            return (
              <View
                key={i}
                style={{
                  marginBottom: 6,
                  padding: 8,
                  borderRadius: 4,
                  borderWidth: 1,
                  borderLeftWidth: 4,
                  backgroundColor: c.bg,
                  borderColor: c.border,
                  borderLeftColor: c.border,
                }}
                wrap={false}
              >
                <View style={{ flexDirection: "row", justifyContent: "space-between" }}>
                  <Text style={{ fontSize: 9, fontFamily: "Helvetica-Bold", color: brand.gray900 }}>
                    {e.summary}
                  </Text>
                  <Text style={pdfStyles.bodySmall}>
                    {e.date} · {SOURCE_LABEL[e.source]}
                    {e.hasPhotos ? " · photo" : ""}
                  </Text>
                </View>
                {e.details.map((d, j) => (
                  <Text key={j} style={[pdfStyles.bodySmall, { marginTop: 2 }]}>
                    {d}
                  </Text>
                ))}
              </View>
            );
          })
        )}

        {/* What to log next */}
        {data.logNext.length > 0 ? (
          <>
            <Text style={pdfStyles.sectionTitle}>What to keep tracking</Text>
            {data.logNext.map((s, i) => (
              <View key={i} style={pdfStyles.listItem}>
                <Text style={pdfStyles.bullet}>•</Text>
                <Text style={pdfStyles.body}>{s}</Text>
              </View>
            ))}
          </>
        ) : null}

        {/* Disclaimer */}
        <View style={pdfStyles.disclaimer}>
          <Text style={pdfStyles.bodySmall}>
            This summary is generated by PawVital from the owner&apos;s logged
            observations. It is not a diagnosis, prognosis, or treatment plan and
            does not replace a veterinary examination. Medication entries are an
            owner-reported history, not dosing advice.
          </Text>
        </View>

        {/* Footer */}
        <View style={pdfStyles.footer} fixed>
          <Text style={pdfStyles.footerText}>PawVital · Owner-reported summary</Text>
          <Text style={pdfStyles.footerText}>Generated {generatedAt}</Text>
        </View>
      </Page>
    </Document>
  );
}
