"use client";

import { useCallback, useEffect, useState } from "react";
import { Pill, ExternalLink, Sparkles } from "lucide-react";
import Card from "@/components/ui/card";
import Button from "@/components/ui/button";
import Badge from "@/components/ui/badge";
import { PrivateTesterQuarantinedSurface } from "@/components/private-tester/quarantined-surface";
import { getPrivateTesterQuarantinedSurface } from "@/lib/private-tester-scope";
import { useAppStore } from "@/store/app-store";

interface SupplementItem {
  name: string;
  purpose: string;
  dosage: string;
  frequency: string;
  brand: string;
  price: string;
  priority: "essential" | "recommended" | "optional";
}

interface SupplementPlan {
  supplements: SupplementItem[];
  nutrition_grade: string;
  monthly_cost: string;
  summary: string;
}

const priorityConfig = {
  essential: { label: "Essential", variant: "danger" as const },
  recommended: { label: "Recommended", variant: "warning" as const },
  optional: { label: "Optional", variant: "info" as const },
};

export default function SupplementsPage() {
  const quarantinedSurface = getPrivateTesterQuarantinedSurface("/supplements");
  const { activePet } = useAppStore();
  const [plan, setPlan] = useState<SupplementPlan | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchPlan = useCallback(async () => {
    if (!activePet) return;
    setLoading(true);
    setError(null);
    try {
      const petPayload = {
        name: activePet.name,
        breed: activePet.breed,
        species: activePet.species,
        age_years: activePet.age_years,
        age_months: activePet.age_months,
        weight: activePet.weight,
        weight_unit: activePet.weight_unit,
        gender: activePet.gender,
        is_neutered: activePet.is_neutered,
        existing_conditions: activePet.existing_conditions ?? [],
        medications: activePet.medications ?? [],
      };
      const res = await fetch("/api/ai/supplements", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pet: petPayload }),
      });
      if (!res.ok) throw new Error("Failed to load plan");
      const data: SupplementPlan = await res.json();
      // Normalize to our item shape (route may return without isActive)
      const normalized: SupplementPlan = {
        ...data,
        supplements: (data.supplements || []).map((s: any) => ({
          name: s.name || "Supplement",
          purpose: s.purpose || "",
          dosage: s.dosage || "",
          frequency: s.frequency || "",
          brand: s.brand || "",
          price: s.price || "",
          priority: (s.priority || "optional") as "essential" | "recommended" | "optional",
        })),
      };
      setPlan(normalized);
    } catch (e) {
      setError("Unable to load personalized plan right now.");
      setPlan(null);
    } finally {
      setLoading(false);
    }
  }, [activePet]);

  useEffect(() => {
    if (activePet) {
      void fetchPlan();
    } else {
      setPlan(null);
    }
  }, [activePet, fetchPlan]);

  const supplements = plan?.supplements ?? [];
  const hasData = supplements.length > 0;

  if (quarantinedSurface) {
    return <PrivateTesterQuarantinedSurface {...quarantinedSurface} />;
  }

  if (!activePet) {
    return (
      <div className="max-w-4xl mx-auto space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Supplement Plan</h1>
          <p className="text-gray-500 mt-1">AI-personalized nutrition recommendations</p>
        </div>
        <Card className="p-8 text-center">
          <p className="text-gray-600">Add a dog profile to generate a personalized supplement plan.</p>
          <a href="/pets" className="inline-block mt-4 text-[#0a7d5b] hover:underline">Go to pet profiles →</a>
        </Card>
        <Card className="p-4 bg-gray-50">
          <p className="text-xs text-gray-500 text-center">
            Supplement recommendations are generated by AI based on your dog&apos;s profile.
            Always consult your veterinarian before starting any new supplement regimen.
            Affiliate links may be used.
          </p>
        </Card>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Supplement Plan</h1>
          <p className="text-gray-500 mt-1">
            AI-personalized nutrition recommendations for {activePet.name}
          </p>
        </div>
        <Button onClick={fetchPlan} loading={loading} disabled={loading}>
          <Sparkles className="w-4 h-4 mr-2" />
          Regenerate Plan
        </Button>
      </div>

      {error ? (
        <Card className="p-4 border-red-200 bg-red-50 text-red-700 text-sm">{error}</Card>
      ) : null}

      {/* Summary cards from live response (or fallback) */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <Card className="p-4 text-center">
          <p className="text-3xl font-bold text-[#0a7d5b]">{supplements.length}</p>
          <p className="text-sm text-gray-500">Recommended Supplements</p>
        </Card>
        <Card className="p-4 text-center">
          <p className="text-3xl font-bold text-[#0a7d5b]">{plan?.monthly_cost ?? "—"}</p>
          <p className="text-sm text-gray-500">Monthly Cost</p>
        </Card>
        <Card className="p-4 text-center">
          <p className="text-3xl font-bold text-[#0a7d5b]">{plan?.nutrition_grade ?? "—"}</p>
          <p className="text-sm text-gray-500">Nutrition Grade</p>
        </Card>
      </div>

      {/* Live summary from route when available */}
      {plan?.summary ? (
        <Card className="p-5 border-[#cfe6dd]">
          <p className="text-sm text-[#0a7d5b] font-medium">Plan summary</p>
          <p className="text-sm text-gray-700 mt-1">{plan.summary}</p>
        </Card>
      ) : null}

      {/* Supplement List (real data or empty state) */}
      <div className="space-y-4">
        {loading ? (
          <Card className="p-6 text-center text-gray-500">Loading personalized plan…</Card>
        ) : hasData ? (
          supplements.map((supp, idx) => (
            <Card key={idx} className="p-6 border-[#e8e2d8]">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl flex items-center justify-center bg-[#e6f3ed]">
                  <Pill className="w-6 h-6 text-[#0a7d5b]" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-gray-900">{supp.name}</h3>
                    <Badge variant={priorityConfig[supp.priority]?.variant ?? "info"}>
                      {priorityConfig[supp.priority]?.label ?? "Optional"}
                    </Badge>
                  </div>
                  <p className="text-sm text-gray-600 mt-1">{supp.purpose}</p>
                  <div className="flex flex-wrap gap-4 mt-3 text-sm text-gray-500">
                    <span>Dose: {supp.dosage}</span>
                    <span>Frequency: {supp.frequency}</span>
                    <span>Brand: {supp.brand}</span>
                    <span className="font-medium text-gray-700">{supp.price}</span>
                  </div>
                </div>
                <a
                  href="#"
                  className="p-2 hover:bg-gray-100 rounded-lg transition-colors self-start"
                  title="Buy this supplement"
                >
                  <ExternalLink className="w-4 h-4 text-gray-400" />
                </a>
              </div>
            </Card>
          ))
        ) : (
          <Card className="p-6 text-center text-gray-600">
            No supplements returned for this profile yet. Try regenerating or add more profile details.
          </Card>
        )}
      </div>

      {/* Disclaimer */}
      <Card className="p-4 bg-gray-50">
        <p className="text-xs text-gray-500 text-center">
          Supplement recommendations are generated by AI based on your dog&apos;s profile.
          Always consult your veterinarian before starting any new supplement regimen.
          Affiliate links may be used.
        </p>
      </Card>
    </div>
  );
}
